dougen_board:
    resource: "@DougenBoardBundle/Controller/"
    type:     annotation
    prefix:   /dougen

acme_hello:
    resource: "@AcmeHelloBundle/Resources/config/routing.yml"
    prefix:   /

contact:
    path:     /contact
    defaults: {_controller: AcmeDemoBundle:Main:contact}
