<?php

namespace Dougen\BoardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function findAllOrderedByName() {
        return $this->getEntityManager()
            ->createQuery('SELECT p FROM DougenBoardBundle:Post p ORDER BY p.name ASC')
            ->getResult();
        
    }
}
